### ISSUE TITLE
FileNotFoundException from file.transferTo(new_file)

### ISSUE THREAD

**Issue by yingwang2** [McGill-DMaS/Kam1n0-Plugin-IDA-Pro#23]
Hi! I'm using development mode of Kam1n0 2.x with window 7, JDK/JRE 1.8, and IntelliJ IDEA.

Under the indexing and binary composition tab, after I click Browse -> Analyze, an alert pops up:

Unsupported format org.springframework.web.multipart.support.StandardMultipartHttpServletRequest$StandardMultipartFile

However, the error shown in the console is "java.io.IOException: java.io.FileNotFoundException: C:\Users\Ying\AppData\Local\Temp\tomcat.3714171793063480935.8571\work\Tomcat\localhost\ROOT\tmp\test\libz.so.1.2.11-gcc-g-O1-m32-fno-pic.bin (The system cannot find the path specified)"

I checked the path above, tmp\test hasn't been created in path \ROOT\. After I manually create path tmp\test\ using windows explorer, the error disappears. After I restart the application, the error shows again because the path "tomcat.xxxx\" has been changed.

So I tried to debug. The error comes from [line 113](https://github.com/McGill-DMaS/Kam1n0-Community/blob/2194aff10db8995d986ce92034a2fef70bca25f4/kam1n0/kam1n0-apps/src/main/java/ca/mcgill/sis/dmas/kam1n0/app/clone/AbastractCloneSearchHandler.java#L113) **_file.transferTo(new_file)_** under the indexing tab, and [line 177](https://github.com/McGill-DMaS/Kam1n0-Community/blob/2194aff10db8995d986ce92034a2fef70bca25f4/kam1n0/kam1n0-apps/src/main/java/ca/mcgill/sis/dmas/kam1n0/app/clone/AbastractCloneSearchHandler.java#L177) under binary composition tab. The location of _file_ in _file.transferTo(new_file)_ is the path C:\Users\Ying\AppData\Local\Temp\tomcat.3714171793063480935.8571\work\Tomcat\localhost\ROOT\ shown above.

The full error info in the console is attached. 
[FileNotFoundException after browing binary file.txt](https://github.com/McGill-DMaS/Kam1n0-Community/files/2497679/FileNotFoundException.after.browing.binary.file.txt)

**Comment by steven-hh-ding** [comment]
Hi Ying. Thanks for the report. Could you try using an absolute path as the data path in Kam1n0.properties?

**Comment by yingwang2** [comment]
Hi Steven, it worked, the default path is E:/testappplatform/ which doesn't exist in my current machine, and I haven't installed IDA pro for now, so I guess it uses the default path of the windows? Thanks!
