### ISSUE TITLE
Documentation on adding additional architectures

### ISSUE THREAD

**Issue by markgllin** [McGill-DMaS/Kam1n0-Plugin-IDA-Pro#32]
Hello! This is amazing work - some really cool stuff!

As a [previous issue](https://github.com/McGill-DMaS/Kam1n0-Community/issues/3) mentioned, there are multitudes of architectures beyond the ones that Kam1n0 currently has support for. In that same issue, there was reference to a document that outlined [how you could create your own processor definition](https://github.com/McGill-DMaS/Kam1n0-Community/issues/3#issuecomment-217207494).

However, it seems like much as changed since that issue was opened as the link is now dead. Do you happen to have updated documentation on how we can go about adding support for other architectures?

Thanks!

**Comment by steven-hh-ding** [comment]
Hey @markgllin . Sorry for my super late reply. I was moving last month. The instruction is here: 

https://github.com/McGill-DMaS/Kam1n0-Community/blob/2194aff10db8995d986ce92034a2fef70bca25f4/kam1n0/kam1n0-commons/src/main/java/ca/mcgill/sis/dmas/kam1n0/impl/disassembly/ArchitectureRepresentationMC68.java#L46-L51

You will need to first create a similar java file in that folder and add in the definition of the instruction set and register names. Then just follow the instruction above. However you do need to rebuild Kam1n0 at this moment. 

Thank you.
