### ISSUE TITLE
IDA Pro Plug-in for Linux

### ISSUE THREAD

**Issue by yuedeji** [McGill-DMaS/Kam1n0-Plugin-IDA-Pro#33]
Hi There,

Great work!

I'm trying to install Kam1n0 on a Linux server machine. I was able to install the Kam1n0 server, but I can not install the "IDA Pro Plug-in" since the provided installer is for Windows. Is it possible to make it work on Linux? 

p.s., we do have an IDA-Pro for Linux.

Best,
Yuede

**Comment by steven-hh-ding** [comment]
Thank you! Could you try unzipping the plugin archive in the release page and put it into the plugin folder of IDA Pro? Then also install cefpython for the python2. Then it should be ready to go.

**Comment by yuedeji** [comment]
Hi Steven,

It works! 
I tried to copy the plug-in to the IDA folder before, but it fails. With cefpython, it works now!

Thanks!
