### ISSUE TITLE
Support for searching multiple binaries

### ISSUE THREAD

**Issue by markgllin** [McGill-DMaS/Kam1n0-Plugin-IDA-Pro#36]
as far as i can tell, Kam1n0 allows you to add multiple files in the Binary Composition tab to search them all against the indexed repo. However, after analysis, the report that is generated only seems to contain the result for the first file.

e.g In the screenshot, I added 6 binaries to be analyzed. However, the resulting report will only contain the analysis for the target file `adler32.o`. Is this an error in my workflow or more of a feature request?

![Screen Shot 2019-09-26 at 10 35 10 AM](https://user-images.githubusercontent.com/10660708/65707336-90516a80-e049-11e9-9488-23e8760e1e82.png)

**Comment by MilesQLi** [comment]
Sorry for the delayed reply. The engine did not support multiple binary composition analysis. I just added this function in the newest pull request. It will be merged after the test is done. Thanks a lot for the feedback!

**Comment by markgllin** [comment]
thanks a lot for looking into it!
